version: "3"

services:
  backend:
    image: {{cookiecutter.docker_image_backend}}
    container_name: {{cookiecutter.docker_image_backend}}
    build:
      context: ./{{cookiecutter.project_slug}}/backend
      dockerfile: ./Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    ports:
      - {{cookiecutter.docker_image_backend_port}}:8000
    env_file:
      - {{cookiecutter.project_slug}}/backend/.env
    volumes:
      - ./{{cookiecutter.project_slug}}/backend/src:/{{cookiecutter.project_slug}}/src
      - ./{{cookiecutter.project_slug}}/uvicorn/config.json:/{{cookiecutter.project_slug}}/uvicorn/config.json:ro
    depends_on:
      - pg
    command: uvicorn --factory src.main:create_app --host 0.0.0.0 --port 8000 --reload --log-config=uvicorn/config.json

  pg:
    image: postgres:15.1
    container_name: {{cookiecutter.docker_image_pg}}
    env_file:
      - ./{{cookiecutter.project_slug}}/pg/.env
    ports:
      - {{cookiecutter.docker_image_pg_port}}:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
